run:
  go: 1.22
  concurrency: 2
  timeout: 1m

linters:
  disable-all: true
  enable:
    - asciicheck # checks that your code does not contain non-ASCII identifiers
    - cyclop # checks function and package cyclomatic complexity
    - dupl # tool for code clone detection
    - errcheck # checking for unchecked errors, these unchecked errors can be critical bugs in some cases
    - goimports # in addition to fixing imports, goimports also formats your code in the same style as gofmt
    - gomodguard # allow and block lists linter for direct Go module dependencies. This is different from depguard where there are different block types for example version constraints and module recommendations
    - goprintffuncname # checks that printf-like functions are named with f at the end
    - gosimple # specializes in simplifying a code
    - govet # reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
    - ineffassign  # detects when assignments to existing variables are not used
    - lll # reports long lines
    - nakedret # finds naked returns in functions greater than a specified function length
    - nolintlint # reports ill-formed or insufficient nolint directives
    - prealloc # [premature optimization, but can be used in some cases] finds slice declarations that could potentially be preallocated
    - staticcheck # is a go vet on steroids, applying a ton of static analysis checks
    - typecheck # like the front-end of a Go compiler, parses and type-checks Go code
    - unconvert # removes unnecessary type conversions
    - unparam # reports unused function parameters
    - unused # checks for unused constants, variables, functions and types
    - whitespace # detects leading and trailing whitespace

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - staticcheck
