// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"gotu-bookstore/internal/app"
	"gotu-bookstore/internal/config"
	"gotu-bookstore/internal/delivery"
	"gotu-bookstore/internal/delivery/middleware"
	"gotu-bookstore/internal/repository"
	"gotu-bookstore/internal/usecase"
)

// Injectors from wire.go:

func ProvideApp() *app.App {
	cfg := config.Get()
	zapLogger := LoggerProvider()
	authJWT := AuthJWTProvider(cfg)
	gormDB := DatabaseProvider(cfg)
	userRepo := repository.NewUserRepo(cfg, gormDB)
	userUC := usecase.NewUserUC(cfg, zapLogger, userRepo, authJWT)
	middlewareMiddleware := middleware.NewMiddleware(cfg, zapLogger, authJWT, userUC)
	authDelivery := delivery.NewAuthDelivery(cfg, userUC)
	userDelivery := delivery.NewUserDelivery(cfg, userUC)
	appApp := app.AppNew(cfg, zapLogger, middlewareMiddleware, authDelivery, userDelivery)
	return appApp
}
