// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"gotu-bookstore/internal/app"
	"gotu-bookstore/internal/config"
	"gotu-bookstore/internal/delivery"
	"gotu-bookstore/internal/delivery/middleware"
	"gotu-bookstore/internal/repository"
	"gotu-bookstore/internal/usecase"
)

// Injectors from wire.go:

func ProvideApp() *app.App {
	cfg := config.Get()
	zapLogger := LoggerProvider()
	authJWT := AuthJWTProvider(cfg)
	gormDB := DatabaseProvider(cfg)
	userRepo := repository.NewUserRepo(cfg, gormDB)
	middlewareMiddleware := middleware.NewMiddleware(cfg, zapLogger, authJWT, userRepo)
	userUC := usecase.NewUserUC(cfg, zapLogger, userRepo, authJWT)
	authDelivery := delivery.NewAuthDelivery(cfg, userUC)
	userDelivery := delivery.NewUserDelivery(cfg, userUC)
	bookRepo := repository.NewBookRepo(cfg, gormDB)
	bookUC := usecase.NewBookUC(zapLogger, bookRepo)
	bookDelivery := delivery.NewBookDelivery(cfg, bookUC)
	orderRepo := repository.NewOrderRepo(cfg, gormDB)
	orderUC := usecase.NewOrderUC(zapLogger, orderRepo, bookRepo)
	orderDelivery := delivery.NewOrderDelivery(cfg, orderUC)
	appApp := app.AppNew(cfg, zapLogger, middlewareMiddleware, authDelivery, userDelivery, bookDelivery, orderDelivery)
	return appApp
}
