// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package provider

import (
	"gotu-bookstore/internal/app"
	"gotu-bookstore/internal/config"
	"gotu-bookstore/internal/delivery/middleware"
)

// Injectors from wire.go:

func ProvideApp() *app.App {
	cfg := config.Get()
	zapLogger := LoggerProvider()
	middlewareMiddleware := middleware.NewMiddleware(cfg, zapLogger)
	appApp := app.AppNew(cfg, zapLogger, middlewareMiddleware)
	return appApp
}
